### ISSUE TITLE
Getting a new error when trying to use this.

### ISSUE THREAD

**Issue by Puddz** [LonicaMewinsky/gif2gif#7]
Traceback (most recent call last):
  File "E:\Games\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\Games\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\Games\stable-diffusion-webui\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "E:\Games\stable-diffusion-webui\modules\scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File "E:\Games\stable-diffusion-webui\extensions\gif2gif\scripts\gif2gif.py", line 260, in run
    color_correction = [modules.processing.setup_color_correction(copy_p.init_images[0])]
AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'init_images'

**Comment by LonicaMewinsky** [comment]
Were you using the txt2img tab at the time? Or img2img?

**Comment by Puddz** [comment]
Txt2img. It's weird. I'm pretty sure I used the extension earlier this morning without issue after updating, then closed sd down. Then tried again and it just started giving me that error.

**Comment by LonicaMewinsky** [comment]
This is indeed a bug introduced with last night's update, that includes functions assuming you're using img2img. I just pushed a change that removes the script as available from txt2img -- it was previously available there to support ControlNet operations when you didn't want to use the image itself as a base. They since added this option:
![image](https://user-images.githubusercontent.com/93007558/221660121-26c94783-f6c6-47fd-ae06-4c0f330ac821.png)
Which fills this requirement. 

Can I ask why you were using txt2img and not img2img? Want to make sure I'm not taking away something useful.

**Comment by LonicaMewinsky** [comment]
You're right-on. There are cases where not using the source image (img2img) with ControlNet is hugely beneficial. That was the reasoning behind having it available in txt2img at all. If you enable "Skip img2img processing when using img2img initial image" in ControlNet settings, you get the same behavior.

**Comment by Puddz** [comment]
Ahh, Okay I understand. That makes sense. Thanks for replying.

**Comment by LonicaMewinsky** [comment]
You bet!
